export const COURSES = [
  {
    id: 1,
    first_name: 'Chrysa',
    last_name: 'Burchfield',
    email: 'cburchfield0@gnu.org',
    gender: 'Bigender',
    course: 'Future Course',
  },
  {
    id: 2,
    first_name: 'Shena',
    last_name: 'Bockman',
    email: 'sbockman1@goodreads.com',
    gender: 'Female',
    course: 'Zoom Course',
  },
  {
    id: 3,
    first_name: 'Daphene',
    last_name: 'Angood',
    email: 'dangood2@twitpic.com',
    gender: 'Genderqueer',
    course: 'Spark Course',
  },
  {
    id: 4,
    first_name: 'Tammy',
    last_name: 'Weaver',
    email: 'tweaver3@auda.org.au',
    gender: 'Female',
    course: 'Future Course',
  },
  {
    id: 5,
    first_name: 'Worthington',
    last_name: 'Croydon',
    email: 'wcroydon4@list-manage.com',
    gender: 'Male',
    course: 'Pioneer Course',
  },
];
